"""v2_schema_completo

Revision ID: 60fc08a85566
Revises: 
Create Date: 2026-06-25 10:54:09.792854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60fc08a85566'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias_relatorio',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('cor', sa.String(length=7), nullable=True),
    sa.Column('icone', sa.String(length=50), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('departamentos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('perfis',
    sa.Column('codigo', sa.String(length=30), nullable=False),
    sa.Column('nome_exibicao', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('nivel_hierarquia', sa.SmallInteger(), nullable=False),
    sa.Column('pode_ser_atribuido', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('codigo')
    )
    op.create_table('credenciais_pbi',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=255), nullable=True),
    sa.Column('client_id', sa.String(length=255), nullable=True),
    sa.Column('client_secret', sa.String(length=500), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('atualizado_por_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['atualizado_por_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # sobrescritas_permissao removida do modelo — drop apenas se ainda existir (bancos migrados do v1)
    conn = op.get_bind()
    tabelas = conn.execute(sa.text("SELECT name FROM sqlite_master WHERE type='table' AND name='sobrescritas_permissao'")).fetchone()
    if tabelas:
        op.drop_table('sobrescritas_permissao')

    # batch_alter_table recria a tabela no SQLite, aplicando a nova FK com CASCADE
    with op.batch_alter_table('membros_grupo_excecao', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_mge_usuario', 'usuarios', ['usuario_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('relatorios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categoria_id', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key('fk_rel_categoria', 'categorias_relatorio', ['categoria_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('departamento_id', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key('fk_usr_departamento', 'departamentos', ['departamento_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_constraint('fk_usr_departamento', type_='foreignkey')
        batch_op.drop_column('departamento_id')

    with op.batch_alter_table('relatorios', schema=None) as batch_op:
        batch_op.drop_constraint('fk_rel_categoria', type_='foreignkey')
        batch_op.drop_column('categoria_id')

    with op.batch_alter_table('membros_grupo_excecao', schema=None) as batch_op:
        batch_op.drop_constraint('fk_mge_usuario', type_='foreignkey')

    op.create_table('sobrescritas_permissao',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('usuario_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('modulo', sa.VARCHAR(length=100), nullable=False),
    sa.Column('pode_visualizar', sa.BOOLEAN(), nullable=True),
    sa.Column('pode_criar', sa.BOOLEAN(), nullable=True),
    sa.Column('pode_editar', sa.BOOLEAN(), nullable=True),
    sa.Column('pode_excluir', sa.BOOLEAN(), nullable=True),
    sa.Column('pode_exportar', sa.BOOLEAN(), nullable=True),
    sa.Column('pode_gerenciar', sa.BOOLEAN(), nullable=True),
    sa.Column('definido_por_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('definido_em', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['definido_por_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'modulo', name=op.f('uq_sp_usuario_modulo'))
    )
    op.drop_table('credenciais_pbi')
    op.drop_table('perfis')
    op.drop_table('departamentos')
    op.drop_table('categorias_relatorio')
    # ### end Alembic commands ###
